services:
  taskboard-api:
    container_name: taskboard-api
    restart: unless-stopped
    build: 
      context: ..
      dockerfile: TaskBoard.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MigrateOnStartup=true
      - ConnectionStrings__TaskBoardDb=Data Source=/app/data/taskboard.db
    volumes:
      - sqlite-data:/app/data

volumes:
  sqlite-data: